# Site settings
title: Blog | RustedBlade
description: "A blog for sharing what we do and how we do it at RustedBlade"
url: "https://www.rustedblade.com/blog"
author:
  name: "RustedBlade"
  email: "rustedbladein@gmail.com"
  url: "https://www.rustedblade.com"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

theme: jekyll-theme-minimal
